### ISSUE TITLE
Hi！Can I get the code？

### ISSUE THREAD

**Issue by SilenceZheng66** [ZhuoLinLi-shu/AGLCN#1]
Hi！Can I get the code？For researching purpose.

**Comment by ZhuoLinLi-shu** [comment]
I'm sorry to have only seen your message. Thank you for your reminder. I almost forgot about this project because I also had difficulty submitting it at that time. I am currently on a business trip and it is not convenient to handle it. If you urgently need it, you can refer to the code of mtgnn, and the basic framework is the same.



来自 MEIZU 20



-------- 原始邮件 --------
发件人：SilenceZheng66 ***@***.***>
时间：2023年10月31日 22:38
收件人：ZhuoLinLi-shu/AGLCN ***@***.***>
抄送：Subscribed ***@***.***>
主题：[ZhuoLinLi-shu/AGLCN] Hi！Can I get the code？ (Issue #1)

**Comment by SilenceZheng66** [comment]
> I'm sorry to have only seen your message. Thank you for your reminder. I almost forgot about this project because I also had difficulty submitting it at that time. I am currently on a business trip and it is not convenient to handle it. If you urgently need it, you can refer to the code of mtgnn, and the basic framework is the same. 来自 MEIZU 20
> […](#)
> -------- 原始邮件 -------- 发件人：SilenceZheng66 ***@***.***> 时间：2023年10月31日 22:38 收件人：ZhuoLinLi-shu/AGLCN ***@***.***> 抄送：Subscribed ***@***.***> 主题：[ZhuoLinLi-shu/AGLCN] Hi！Can I get the code？ (Issue #1)

Thank you！ That will be very helpful and looking forward to your code release!

**Comment by ZhuoLinLi-shu** [comment]
I am currently on a business trip and will handle it in about a week. If you urgently need it, please refer to the code for mtgnn.



来自 MEIZU 20



-------- 原始邮件 --------
发件人：SilenceZheng66 ***@***.***>
时间：2023年10月31日 22:38
收件人：ZhuoLinLi-shu/AGLCN ***@***.***>
抄送：Subscribed ***@***.***>
主题：[ZhuoLinLi-shu/AGLCN] Hi！Can I get the code？ (Issue #1)

**Comment by ZhuoLinLi-shu** [comment]
The code has been uploaded

**Comment by SilenceZheng66** [comment]
> The code has been uploaded

Thank you! But your code seems lack of module "Second_paper_final", so the project cannot be running。

**Comment by SilenceZheng66** [comment]
> The code has been uploaded

And I hope you can publish the best training settings, currently the training command seems cannot have a good performance that the paper given.

**Comment by ZhuoLinLi-shu** [comment]
I have fixed the code and thank you for your reminder

**Comment by ZhuoLinLi-shu** [comment]
I have provided the training log with detailed parameters

**Comment by ZhuoLinLi-shu** [comment]
For quick verification, I turned down the training epoch, you can set the epoch to 100

**Comment by SilenceZheng66** [comment]
> For quick verification, I turned down the training epoch, you can set the epoch to 100

Thank you! That's very efficient and helpful!
